version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwords
      POSTGRES_DB: event_ticketing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - app-network

  app:
    build: .
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    env_file:
      - .env  # Reference the .env file
    depends_on:
      - postgres-db
    networks:
      - app-network
    volumes:
      - ./images:/app/images
      - ./qr-codes:/app/qr-codes
      - ./wait-for-it.sh:/app/wait-for-it.sh

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
